### PR TITLE
Align vert.x versions

### LINKED ISSUE #685: Version 3.2.0 exports vertx-core 4.3.4
After upgrading from 2.28.0 to 3.2.0, I'm getting `NoClassDefFoundError`s for certain classes used in `vertx-web`:4.3.6 since a dependency on `vertx-core`:4.3.6 is required, but for some reason between bindings version 2.28.0 and 3.2.0, the exported `vertx-core` version seems to have downgraded.

### PR DESCRIPTION
**Pull request by cescoffier**
Fix #685

### CODE REVIEW

**Comment by cescoffier** [comment]
Funny, the issue only happened in the 3.x (main) branch. 2.x is correct...

**Review by jponge — APPROVED** [review]
