### ISSUE TITLE
Version 3.2.0 exports vertx-core 4.3.4

### ISSUE THREAD

**Issue by cameronprater** [smallrye/smallrye-mutiny-vertx-bindings#685]
After upgrading from 2.28.0 to 3.2.0, I'm getting `NoClassDefFoundError`s for certain classes used in `vertx-web`:4.3.6 since a dependency on `vertx-core`:4.3.6 is required, but for some reason between bindings version 2.28.0 and 3.2.0, the exported `vertx-core` version seems to have downgraded.

**Comment by cameronprater** [comment]
I know nothing about how this project works, but I think the conflict is here:
https://github.com/smallrye/smallrye-mutiny-vertx-bindings/blob/main/vertx-mutiny-clients/vertx-mutiny-core/pom.xml#L18

whereas `vertx.version` in `pom.xml` is 4.3.6

**Comment by cescoffier** [comment]
The 2.x version is using Mutiny 1.x - that's the one currently used in Quarkus. 
The 3.x version is using Mutiny 3.x - it will be used in Quarkus 3.x. Do not use them (in quarkus) yet.

**Comment by cameronprater** [comment]
Again, I believe that's due to the error in that pom I showed above. You are generating bindings for 4.3.6 for all vertx libraries other than core which is generating bindings for 4.3.4 due to the issue in the `pom` I showed above.

**Comment by cescoffier** [comment]
I see! We have a duplicated Vert.x version.
